### ISSUE TITLE
Support for UUID Data Type

### ISSUE THREAD

**Issue by rgauss** [usnistgov/metaschema-java#2]
# User Story:

As a Metaschema consumer, I want to be able to leverage a UUID data type so that I can accommodate schemas that require them.

## Goals:

The primary objective is to be able to accommodate changes to a UUID in the OSCAL schema using [liboscal-java](https://github.com/usnistgov/liboscal-java).

## Dependencies:

None

## Acceptance Criteria

- ~~[ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.~~
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
@rgauss The latest in master is a working version of the metaschema binding that will work with the latest OSCAL 1.0.0-rc1 schema. I plan to release this soon once I do a bit more testing. Can you give this a try?
