### ISSUE TITLE
Support Metapath sequence functions

### ISSUE THREAD

**Issue by david-waltermire** [usnistgov/metaschema-java#237]
# User Story:

As a Metaschema constraint author, I need to be able to manipulate sequences in Metapaths used to target and perform constraint checking.

## Goals:

Add support for Metapath functions that operate on sequences and associated JUnit tests.

The functions to implement are:

- [fn:empty](https://www.w3.org/TR/xpath-functions-31/#func-empty)
  - [x] `fn:empty($arg as item()*) as xs:boolean`
  - [x] Unit tests
- [fn:head](https://www.w3.org/TR/xpath-functions-31/#func-head)
  - [x] `fn:head($arg as item()*) as item()?`
  - [x] Unit tests
- [fn:tail](https://www.w3.org/TR/xpath-functions-31/#func-tail)
  - [x] `fn:tail($arg as item()*) as item()*`
  - [x] Unit tests
- [fn:insert-before](https://www.w3.org/TR/xpath-functions-31/#func-insert-before)
  - [x] `fn:insert-before($target as item()*, $position as xs:integer, $inserts as item()*) as item()*`
  - [x] Unit tests
- [fn:remove](https://www.w3.org/TR/xpath-functions-31/#func-remove)
  - [x] `fn:remove($target as item()*, $position as xs:integer) as item()*`
  - [x] Unit tests
- [fn:reverse](https://www.w3.org/TR/xpath-functions-31/#func-reverse)
  - [x] `fn:reverse($arg as item()*) as item()*`
  - [x] Unit tests

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, you want to assign @Arminta-Jenkins-NIST and I?
