### ISSUE TITLE
Implement additional Metapath syntax

### ISSUE THREAD

**Issue by david-waltermire** [usnistgov/metaschema-java#238]
# User Story:

As a Metaschema Metapath constraints author, I need a robust Metapath implementation that implements more of the XPath 3.1 syntax.

## Goals:

Implement the following:

- Metapath [if](https://www.w3.org/TR/xpath-31/#id-conditionals)  expressions
  - [x] Unit tests
- [x] Metapath [for](https://www.w3.org/TR/xpath-31/#id-for-expressions)  expressions
  - [x] Unit tests
- [x] Metapath [simple map (!)](https://www.w3.org/TR/xpath-31/#id-map-operator)  expressions
  - [x] Unit tests

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
I would be interested in volunteering to handle simple map tasks later sometime in the near to medium-term future if you are up for it, @david-waltermire-nist. It would be a good learning experience for me.
