### ISSUE TITLE
Site Header Github Link is Incorrect

### ISSUE THREAD

**Issue by rgauss** [usnistgov/metaschema-java#4]
# Describe the bug

The Github link in the header of the site points to the swid project.

# Who is the bug affecting?

Those viewing the [Metaschema Java Tools site](ev.azure.com/easydynamics/mark-public-site). 

# What is affected by this bug?

The [Metaschema Java Tools site](ev.azure.com/easydynamics/mark-public-site) header.

# When does this occur?

Always.

# How do we replicate the issue?
1. Navigate to the [public site](dev.azure.com/easydynamics/mark-public-site)
2. Click on the 'Github project' link in the header.

## Expected Behavior
3. The [metaschema-java](https://github.com/usnistgov/metaschema-java) project is displayed

## Actual Behavior
3. The [swid-tools](https://github.com/usnistgov/swid-tools/) project is displayed

**Comment by david-waltermire-nist** [comment]
This was fixed by PR #4.
